# Generated by Django 3.2.21 on 2023-09-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=256)),
                ('email', models.TextField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(verbose_name='created_time')),
                ('updated_time', models.DateTimeField(verbose_name='updated_time')),
            ],
        ),
    ]
