# Generated by Django 3.2.21 on 2023-09-06 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_rename_name_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='updated_time'),
        ),
    ]
